### ISSUE TITLE
Digi sweep has stolen 100,000 to the donation address. Please kindly refund my Digi!

### ISSUE THREAD

**Issue by BlockchainEconomy** [digiassetX/digisweep#5]
Greetings,

May I start by saying thank you for your sweeping service, it has helped solve a big problem for me.

However, it has created an even bigger on that should be easy to solve.

I was using the mctriva sweep service and the vast majority of my funds got sent to the donation address somehow.

While I dont mind making a donation, this is a catastrophic loss due to the amount.

100081.66903601 DGB were sent to the donation address without my consent. Perhaps I made an error, but the last sweeps I did, didnt have this problem.

Transaction #
5aefb68e61269b01bb833e10dae1c4221efc31ed254927ebc5242d98f172733d

Link:
https://digibyteblockexplorer.com/address/D9RVKBjzRvnzUUTHxZBNZ3kfAHrmci1v76

Would you please kindly refund me 99081.66903601 DGB to address:
dgb1qr6c2jl47pnguvuaf20kku20p5vvs40skkx079p

I would be happy to leave 1000 DGB as a donation.

Thank you kindly for your help and consideration..

Kind regards

WF

**Comment by mctrivia** [comment]
There was a bug in the old version.  Since it is non functional I am not sure how you managed to send with it.  I sent you a refund on txid:  c5d11df568c43b7857595c7a8ebd187f2ff741adf7a74750c13ec891e945f05d
